apiVersion: v1
kind: Service
metadata:
  name: {{ include "coraza-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "coraza-operator.selectorLabels" . | nindent 4 }}
