apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coraza-controller-manager
  namespace: coraza-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: coraza-controller-manager
      app.kubernetes.io/name: coraza
